modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Gluton-Official/ExperiencedAnvils/issues"
[[mods]]
modId="expanvils"
version="${file.jarVersion}"
displayName="Experienced Anvils"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Gluton-Official/ExperiencedAnvils"
logoFile="logo.png"
authors="Gluton"
description='''
Removes the maximum level on anvils.
'''